services:
  api:
    build: .
    command: ["fastapi", "dev", "--host", "0.0.0.0", "main.py"]
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ../data:/data
