// The cross-repo fixture exchange: which file in `pgb` each real subgraph here
// is the source of, and how to read the pair back.
//
// The two repositories are one contract in two halves. This one produces
// documents and band payloads; `pgb` parses them. Nothing checked that they
// agreed until #25, and a wire-format break reached the frontend as an error
// card at best and a silently wrong picture at worst.
//
// So both encodings of all five real subgraphs are committed under
// `tests/fixtures/exchange/`, generated by `npm run fixtures:exchange` from the
// inputs already in `tests/fixtures/seqtubemap/`, and `pgb` commits a copy of
// each and parses it. The file names are **`pgb`'s**, not this repository's, so
// that the exchange is a copy and not a translation:
//
//     cp tests/fixtures/exchange/* ../pgb/src/tubemap/__tests__/fixtures/
//
// See `../fixtures/exchange/README.md` for what they are and when to re-generate
// them.
import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { join } from "node:path";

import { repoRoot } from "./golden-cases.mjs";
import { realCases } from "./real-cases.mjs";

export const exchangeDir = join(repoRoot, "tests", "fixtures", "exchange");

/**
 * This repository's fixture name, and the stem `pgb` files the pair under.
 *
 * Same order as `realCases` — smallest first — and the same five regions. The
 * two spellings of a region differ because the two repositories name a fixture
 * after different things: this one after the subgraph the server wrote, `pgb`
 * after the tube map it draws, which for two of them is a **minigraph node**
 * (`5514`, `5520`) rather than a coordinate range. Neither name is derivable
 * from the other, so the mapping is written down once, here.
 */
export const exchangeStems = new Map([
  ["subgraph_chr8_78771162_78771252_v2_with_walk", "stm-chr8-78771162-78771252"],
  ["subgraph_chr1_25331046_25331646_v2_with_walk", "stm-chr1-25331046-25331646"],
  ["subgraph_chr8_10079054_10080461_v2_with_walk", "stm-chr8-10079054-10080461"],
  ["subgraph_chr1_25301271_25309238_v2_with_walk", "stm-node-5514-chr1-25301271-25309238"],
  ["subgraph_chr1_25331646_25335796_v2_with_walk", "stm-node-5520-chr1-25331646-25335796"],
]);

/** The stem `pgb` files one of this repository's fixtures under. */
export function stemFor(name) {
  const stem = exchangeStems.get(name);
  if (stem === undefined) throw new Error(`no exchange stem for ${name}`);
  return stem;
}

/** The band payload, as the bytes `/seqtubemap?format=bands` returns. */
export function payloadPath(name) {
  return join(exchangeDir, `${stemFor(name)}.bands`);
}

/**
 * The document from the *same render* as that payload.
 *
 * `.paired` is `pgb`'s word and it is load-bearing there: five documents fetched
 * from the server in August already sit in that directory under the bare stem,
 * from a layout two increments ago. A payload paired with one of those would
 * compare two different pictures. Gzipped, because 29.93 MB of XML is not
 * committable and 3 MB is — the same trade the band-data baselines make.
 */
export function documentPath(name) {
  return join(exchangeDir, `${stemFor(name)}.paired.svg.gz`);
}

/** The committed payload for one region. */
export function readExchangePayload(name) {
  return new Uint8Array(readFileSync(payloadPath(name)));
}

/** The committed document for one region, decompressed. */
export function readExchangeDocument(name) {
  return gunzipSync(readFileSync(documentPath(name))).toString("utf8");
}

/** Every region in the exchange, smallest first. */
export const exchangeCases = realCases;
